<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Core\ArsefRules.cs" Link="ArsefRules.cs" />
    <Compile Include="..\..\Core\DivaSchema.cs" Link="DivaSchema.cs" />
  </ItemGroup>
</Project>
